Summary: fix8 FIX protocol library 
Name: fix8
Version: 0.6.7
Release: 0
License: GPL
Group: Productivity/Networking
Source0: http://somewhere/Foobar/%{name}-%{version}.tar.gz
URL: http://somewhere
BuildRoot: %{_tmppath}/%{name}-root
Prefix: %{_prefix}

%description
fix8 - a library for interfacing to FIX gateways for stock exchanges

%prep
%setup -n %{name}-%{version}

%build
%configure
make

%install
%makeinstall

%clean
rm -rf $RPM_BUILD_ROOT
#
%files
%defattr(-,root,root)

/usr/bin/f8c
/usr/bin/f8print
/usr/bin/f8test
/usr/bin/harness
/usr/bin/hfprint
/usr/bin/hftest
/usr/lib64/libfix8.la
/usr/lib64/libfix8.so
/usr/lib64/libfix8.so.0
/usr/lib64/libfix8.so.0.0.0
/usr/lib64/libhftest.la
/usr/lib64/libhftest.so
/usr/lib64/libhftest.so.0
/usr/lib64/libhftest.so.0.0.0
/usr/lib64/libmyfix.la
/usr/lib64/libmyfix.so
/usr/lib64/libmyfix.so.0
/usr/lib64/libmyfix.so.0.0.0
/usr/include/fix8/configuration.hpp
/usr/include/fix8/connection.hpp
/usr/include/fix8/consolemenu.hpp
/usr/include/fix8/f8allocator.hpp
/usr/include/fix8/f8config.h
/usr/include/fix8/f8exception.hpp
/usr/include/fix8/f8includes.hpp
/usr/include/fix8/f8types.hpp
/usr/include/fix8/f8utils.hpp
/usr/include/fix8/field.hpp
/usr/include/fix8/gzstream.hpp
/usr/include/fix8/logger.hpp
/usr/include/fix8/memory.hpp
/usr/include/fix8/message.hpp
/usr/include/fix8/persist.hpp
/usr/include/fix8/session.hpp
/usr/include/fix8/sessionwrapper.hpp
/usr/include/fix8/thread.hpp
/usr/include/fix8/tickval.hpp
/usr/include/fix8/timer.hpp
/usr/include/fix8/traits.hpp
/usr/include/fix8/usage.hpp
/usr/include/fix8/xml.hpp
/usr/share/fix8/html/FIX50SP2_8xml.html
/usr/share/fix8/html/FIX50SP2_8xml_source.html
/usr/share/fix8/html/Myfix__classes_8cpp.html
/usr/share/fix8/html/Myfix__classes_8cpp.js
/usr/share/fix8/html/Myfix__classes_8cpp_source.html
/usr/share/fix8/html/Myfix__classes_8hpp.html
/usr/share/fix8/html/Myfix__classes_8hpp_source.html
/usr/share/fix8/html/Myfix__router_8hpp.html
/usr/share/fix8/html/Myfix__router_8hpp_source.html
/usr/share/fix8/html/Myfix__traits_8cpp.html
/usr/share/fix8/html/Myfix__traits_8cpp_source.html
/usr/share/fix8/html/Myfix__types_8cpp.html
/usr/share/fix8/html/Myfix__types_8cpp_source.html
/usr/share/fix8/html/Myfix__types_8hpp.html
/usr/share/fix8/html/Myfix__types_8hpp_source.html
/usr/share/fix8/html/Perf__classes_8cpp.html
/usr/share/fix8/html/Perf__classes_8cpp.js
/usr/share/fix8/html/Perf__classes_8cpp_source.html
/usr/share/fix8/html/Perf__classes_8hpp.html
/usr/share/fix8/html/Perf__classes_8hpp_source.html
/usr/share/fix8/html/Perf__router_8hpp.html
/usr/share/fix8/html/Perf__router_8hpp_source.html
/usr/share/fix8/html/Perf__traits_8cpp.html
/usr/share/fix8/html/Perf__traits_8cpp_source.html
/usr/share/fix8/html/Perf__types_8cpp.html
/usr/share/fix8/html/Perf__types_8cpp_source.html
/usr/share/fix8/html/Perf__types_8hpp.html
/usr/share/fix8/html/Perf__types_8hpp_source.html
/usr/share/fix8/html/annotated.html
/usr/share/fix8/html/annotated.js
/usr/share/fix8/html/bc_s.png
/usr/share/fix8/html/classFIX8_1_1AsyncSocket-members.html
/usr/share/fix8/html/classFIX8_1_1AsyncSocket.html
/usr/share/fix8/html/classFIX8_1_1AsyncSocket.js
/usr/share/fix8/html/classFIX8_1_1BCLogger-members.html
/usr/share/fix8/html/classFIX8_1_1BCLogger.html
/usr/share/fix8/html/classFIX8_1_1BCLogger.js
/usr/share/fix8/html/classFIX8_1_1BCLogger.png
/usr/share/fix8/html/classFIX8_1_1BDBPersister-members.html
/usr/share/fix8/html/classFIX8_1_1BDBPersister.html
/usr/share/fix8/html/classFIX8_1_1BDBPersister.js
/usr/share/fix8/html/classFIX8_1_1BDBPersister.png
/usr/share/fix8/html/classFIX8_1_1BaseField-members.html
/usr/share/fix8/html/classFIX8_1_1BaseField.html
/usr/share/fix8/html/classFIX8_1_1BaseField.js
/usr/share/fix8/html/classFIX8_1_1BaseField.png
/usr/share/fix8/html/classFIX8_1_1ClientConnection-members.html
/usr/share/fix8/html/classFIX8_1_1ClientConnection.html
/usr/share/fix8/html/classFIX8_1_1ClientConnection.js
/usr/share/fix8/html/classFIX8_1_1ClientConnection.png
/usr/share/fix8/html/classFIX8_1_1ClientSession-members.html
/usr/share/fix8/html/classFIX8_1_1ClientSession.html
/usr/share/fix8/html/classFIX8_1_1ClientSession.js
/usr/share/fix8/html/classFIX8_1_1ClientSession.png
/usr/share/fix8/html/classFIX8_1_1Configuration-members.html
/usr/share/fix8/html/classFIX8_1_1Configuration.html
/usr/share/fix8/html/classFIX8_1_1Configuration.js
/usr/share/fix8/html/classFIX8_1_1Configuration.png
/usr/share/fix8/html/classFIX8_1_1Connection-members.html
/usr/share/fix8/html/classFIX8_1_1Connection.html
/usr/share/fix8/html/classFIX8_1_1Connection.js
/usr/share/fix8/html/classFIX8_1_1Connection.png
/usr/share/fix8/html/classFIX8_1_1ConsoleMenu-members.html
/usr/share/fix8/html/classFIX8_1_1ConsoleMenu.html
/usr/share/fix8/html/classFIX8_1_1ConsoleMenu.js
/usr/share/fix8/html/classFIX8_1_1CustomFields-members.html
/usr/share/fix8/html/classFIX8_1_1CustomFields.html
/usr/share/fix8/html/classFIX8_1_1CustomFields.js
/usr/share/fix8/html/classFIX8_1_1FIXReader-members.html
/usr/share/fix8/html/classFIX8_1_1FIXReader.html
/usr/share/fix8/html/classFIX8_1_1FIXReader.js
/usr/share/fix8/html/classFIX8_1_1FIXReader.png
/usr/share/fix8/html/classFIX8_1_1FIXWriter-members.html
/usr/share/fix8/html/classFIX8_1_1FIXWriter.html
/usr/share/fix8/html/classFIX8_1_1FIXWriter.js
/usr/share/fix8/html/classFIX8_1_1FIXWriter.png
/usr/share/fix8/html/classFIX8_1_1Field-members.html
/usr/share/fix8/html/classFIX8_1_1Field.html
/usr/share/fix8/html/classFIX8_1_1Field.png
/usr/share/fix8/html/classFIX8_1_1FieldTraits-members.html
/usr/share/fix8/html/classFIX8_1_1FieldTraits.html
/usr/share/fix8/html/classFIX8_1_1FieldTraits.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01Boolean_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01Boolean_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01Boolean_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01Boolean_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01DayOfMonth_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01DayOfMonth_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01DayOfMonth_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01DayOfMonth_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01Length_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01Length_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01Length_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01Length_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01LocalMktDate_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01LocalMktDate_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01LocalMktDate_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01LocalMktDate_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01MonthYear_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01MonthYear_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01MonthYear_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01MonthYear_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01MultipleCharValue_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01MultipleCharValue_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01MultipleCharValue_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01MultipleCharValue_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01NumInGroup_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01NumInGroup_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01NumInGroup_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01NumInGroup_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01Qty_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01Qty_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01Qty_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01Qty_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01SeqNum_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01SeqNum_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01SeqNum_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01SeqNum_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01TZTimeOnly_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01TZTimeOnly_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01TZTimeOnly_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01TZTimeOnly_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01TZTimestamp_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01TZTimestamp_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01TZTimestamp_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01TZTimestamp_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01TagNum_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01TagNum_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01TagNum_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01TagNum_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01UTCDateOnly_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01UTCDateOnly_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01UTCDateOnly_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01UTCDateOnly_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01UTCTimeOnly_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01UTCTimeOnly_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01UTCTimeOnly_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01UTCTimeOnly_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01UTCTimestamp_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01UTCTimestamp_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01UTCTimestamp_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01UTCTimestamp_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01char_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01char_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01char_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01char_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01data_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01data_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01data_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01data_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01double_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01double_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01double_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01double_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01f8String_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01f8String_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01f8String_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01f8String_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1Field_3_01int_00_01field_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01int_00_01field_01_4.html
/usr/share/fix8/html/classFIX8_1_1Field_3_01int_00_01field_01_4.js
/usr/share/fix8/html/classFIX8_1_1Field_3_01int_00_01field_01_4.png
/usr/share/fix8/html/classFIX8_1_1FileLogger-members.html
/usr/share/fix8/html/classFIX8_1_1FileLogger.html
/usr/share/fix8/html/classFIX8_1_1FileLogger.js
/usr/share/fix8/html/classFIX8_1_1FileLogger.png
/usr/share/fix8/html/classFIX8_1_1FilePersister-members.html
/usr/share/fix8/html/classFIX8_1_1FilePersister.html
/usr/share/fix8/html/classFIX8_1_1FilePersister.js
/usr/share/fix8/html/classFIX8_1_1FilePersister.png
/usr/share/fix8/html/classFIX8_1_1GeneratedTable-members.html
/usr/share/fix8/html/classFIX8_1_1GeneratedTable.html
/usr/share/fix8/html/classFIX8_1_1GeneratedTable.js
/usr/share/fix8/html/classFIX8_1_1GroupBase-members.html
/usr/share/fix8/html/classFIX8_1_1GroupBase.html
/usr/share/fix8/html/classFIX8_1_1GroupBase.js
/usr/share/fix8/html/classFIX8_1_1IntervalTimer-members.html
/usr/share/fix8/html/classFIX8_1_1IntervalTimer.html
/usr/share/fix8/html/classFIX8_1_1IntervalTimer.js
/usr/share/fix8/html/classFIX8_1_1Logger-members.html
/usr/share/fix8/html/classFIX8_1_1Logger.html
/usr/share/fix8/html/classFIX8_1_1Logger.js
/usr/share/fix8/html/classFIX8_1_1Logger.png
/usr/share/fix8/html/classFIX8_1_1MemoryPersister-members.html
/usr/share/fix8/html/classFIX8_1_1MemoryPersister.html
/usr/share/fix8/html/classFIX8_1_1MemoryPersister.js
/usr/share/fix8/html/classFIX8_1_1MemoryPersister.png
/usr/share/fix8/html/classFIX8_1_1MemoryPool-members.html
/usr/share/fix8/html/classFIX8_1_1MemoryPool.html
/usr/share/fix8/html/classFIX8_1_1MemoryPool.js
/usr/share/fix8/html/classFIX8_1_1Message-members.html
/usr/share/fix8/html/classFIX8_1_1Message.html
/usr/share/fix8/html/classFIX8_1_1Message.js
/usr/share/fix8/html/classFIX8_1_1Message.png
/usr/share/fix8/html/classFIX8_1_1MessageBase-members.html
/usr/share/fix8/html/classFIX8_1_1MessageBase.html
/usr/share/fix8/html/classFIX8_1_1MessageBase.js
/usr/share/fix8/html/classFIX8_1_1MessageBase.png
/usr/share/fix8/html/classFIX8_1_1Persister-members.html
/usr/share/fix8/html/classFIX8_1_1Persister.html
/usr/share/fix8/html/classFIX8_1_1Persister.js
/usr/share/fix8/html/classFIX8_1_1Persister.png
/usr/share/fix8/html/classFIX8_1_1PipeLogger-members.html
/usr/share/fix8/html/classFIX8_1_1PipeLogger.html
/usr/share/fix8/html/classFIX8_1_1PipeLogger.js
/usr/share/fix8/html/classFIX8_1_1PipeLogger.png
/usr/share/fix8/html/classFIX8_1_1RealmObject-members.html
/usr/share/fix8/html/classFIX8_1_1RealmObject.html
/usr/share/fix8/html/classFIX8_1_1RealmObject.js
/usr/share/fix8/html/classFIX8_1_1RealmObject.png
/usr/share/fix8/html/classFIX8_1_1RegExp-members.html
/usr/share/fix8/html/classFIX8_1_1RegExp.html
/usr/share/fix8/html/classFIX8_1_1RegExp.js
/usr/share/fix8/html/classFIX8_1_1RegMatch-members.html
/usr/share/fix8/html/classFIX8_1_1RegMatch.html
/usr/share/fix8/html/classFIX8_1_1RegMatch.js
/usr/share/fix8/html/classFIX8_1_1RegionManager-members.html
/usr/share/fix8/html/classFIX8_1_1RegionManager.html
/usr/share/fix8/html/classFIX8_1_1RegionManager.js
/usr/share/fix8/html/classFIX8_1_1ReliableClientSession-members.html
/usr/share/fix8/html/classFIX8_1_1ReliableClientSession.html
/usr/share/fix8/html/classFIX8_1_1ReliableClientSession.js
/usr/share/fix8/html/classFIX8_1_1ReliableClientSession.png
/usr/share/fix8/html/classFIX8_1_1Router-members.html
/usr/share/fix8/html/classFIX8_1_1Router.html
/usr/share/fix8/html/classFIX8_1_1Router.js
/usr/share/fix8/html/classFIX8_1_1ServerConnection-members.html
/usr/share/fix8/html/classFIX8_1_1ServerConnection.html
/usr/share/fix8/html/classFIX8_1_1ServerConnection.js
/usr/share/fix8/html/classFIX8_1_1ServerConnection.png
/usr/share/fix8/html/classFIX8_1_1ServerSession-members.html
/usr/share/fix8/html/classFIX8_1_1ServerSession.html
/usr/share/fix8/html/classFIX8_1_1ServerSession.js
/usr/share/fix8/html/classFIX8_1_1ServerSession.png
/usr/share/fix8/html/classFIX8_1_1Session-members.html
/usr/share/fix8/html/classFIX8_1_1Session.html
/usr/share/fix8/html/classFIX8_1_1Session.js
/usr/share/fix8/html/classFIX8_1_1SessionID-members.html
/usr/share/fix8/html/classFIX8_1_1SessionID.html
/usr/share/fix8/html/classFIX8_1_1SessionID.js
/usr/share/fix8/html/classFIX8_1_1SessionInstance-members.html
/usr/share/fix8/html/classFIX8_1_1SessionInstance.html
/usr/share/fix8/html/classFIX8_1_1SessionInstance.js
/usr/share/fix8/html/classFIX8_1_1SingleLogger-members.html
/usr/share/fix8/html/classFIX8_1_1SingleLogger.html
/usr/share/fix8/html/classFIX8_1_1SingleLogger.js
/usr/share/fix8/html/classFIX8_1_1SingleLogger.png
/usr/share/fix8/html/classFIX8_1_1Singleton-members.html
/usr/share/fix8/html/classFIX8_1_1Singleton.html
/usr/share/fix8/html/classFIX8_1_1Singleton.js
/usr/share/fix8/html/classFIX8_1_1Thread-members.html
/usr/share/fix8/html/classFIX8_1_1Thread.html
/usr/share/fix8/html/classFIX8_1_1Thread.js
/usr/share/fix8/html/classFIX8_1_1Thread.png
/usr/share/fix8/html/classFIX8_1_1Thread_1_1__helper-members.html
/usr/share/fix8/html/classFIX8_1_1Thread_1_1__helper.html
/usr/share/fix8/html/classFIX8_1_1Thread_1_1__helper.js
/usr/share/fix8/html/classFIX8_1_1Thread_3_4-members.html
/usr/share/fix8/html/classFIX8_1_1Thread_3_4.html
/usr/share/fix8/html/classFIX8_1_1Thread_3_4.js
/usr/share/fix8/html/classFIX8_1_1Thread_3_4.png
/usr/share/fix8/html/classFIX8_1_1Thread_3_4_1_1__helper-members.html
/usr/share/fix8/html/classFIX8_1_1Thread_3_4_1_1__helper.html
/usr/share/fix8/html/classFIX8_1_1Thread_3_4_1_1__helper.js
/usr/share/fix8/html/classFIX8_1_1Tickval-members.html
/usr/share/fix8/html/classFIX8_1_1Tickval.html
/usr/share/fix8/html/classFIX8_1_1Tickval.js
/usr/share/fix8/html/classFIX8_1_1Timer-members.html
/usr/share/fix8/html/classFIX8_1_1Timer.html
/usr/share/fix8/html/classFIX8_1_1Timer.js
/usr/share/fix8/html/classFIX8_1_1TimerEvent-members.html
/usr/share/fix8/html/classFIX8_1_1TimerEvent.html
/usr/share/fix8/html/classFIX8_1_1TimerEvent.js
/usr/share/fix8/html/classFIX8_1_1TypedRealm-members.html
/usr/share/fix8/html/classFIX8_1_1TypedRealm.html
/usr/share/fix8/html/classFIX8_1_1TypedRealm.js
/usr/share/fix8/html/classFIX8_1_1TypedRealm.png
/usr/share/fix8/html/classFIX8_1_1__threadbase-members.html
/usr/share/fix8/html/classFIX8_1_1__threadbase.html
/usr/share/fix8/html/classFIX8_1_1__threadbase.js
/usr/share/fix8/html/classFIX8_1_1__threadbase.png
/usr/share/fix8/html/classFIX8_1_1bcostream-members.html
/usr/share/fix8/html/classFIX8_1_1bcostream.html
/usr/share/fix8/html/classFIX8_1_1bcostream.js
/usr/share/fix8/html/classFIX8_1_1bcoutbuf-members.html
/usr/share/fix8/html/classFIX8_1_1bcoutbuf.html
/usr/share/fix8/html/classFIX8_1_1bcoutbuf.js
/usr/share/fix8/html/classFIX8_1_1ebitset-members.html
/usr/share/fix8/html/classFIX8_1_1ebitset.html
/usr/share/fix8/html/classFIX8_1_1ebitset.js
/usr/share/fix8/html/classFIX8_1_1ebitset__r-members.html
/usr/share/fix8/html/classFIX8_1_1ebitset__r.html
/usr/share/fix8/html/classFIX8_1_1ebitset__r.js
/usr/share/fix8/html/classFIX8_1_1f8Allocator-members.html
/usr/share/fix8/html/classFIX8_1_1f8Allocator.html
/usr/share/fix8/html/classFIX8_1_1f8Allocator.js
/usr/share/fix8/html/classFIX8_1_1f8Allocator.png
/usr/share/fix8/html/classFIX8_1_1f8Exception-members.html
/usr/share/fix8/html/classFIX8_1_1f8Exception.html
/usr/share/fix8/html/classFIX8_1_1f8Exception.js
/usr/share/fix8/html/classFIX8_1_1f8Exception.png
/usr/share/fix8/html/classFIX8_1_1fdinbuf-members.html
/usr/share/fix8/html/classFIX8_1_1fdinbuf.html
/usr/share/fix8/html/classFIX8_1_1fdinbuf.js
/usr/share/fix8/html/classFIX8_1_1fdoutbuf-members.html
/usr/share/fix8/html/classFIX8_1_1fdoutbuf.html
/usr/share/fix8/html/classFIX8_1_1fdoutbuf.js
/usr/share/fix8/html/classFIX8_1_1fptrostream-members.html
/usr/share/fix8/html/classFIX8_1_1fptrostream.html
/usr/share/fix8/html/classFIX8_1_1fptrostream.js
/usr/share/fix8/html/classFIX8_1_1presorted__set-members.html
/usr/share/fix8/html/classFIX8_1_1presorted__set.html
/usr/share/fix8/html/classFIX8_1_1presorted__set.js
/usr/share/fix8/html/classFIX8_1_1presorted__set_3_01unsigned_01short_00_01FieldTrait_00_01FieldTrait_1_1Compare_01_4-members.html
/usr/share/fix8/html/classFIX8_1_1presorted__set_3_01unsigned_01short_00_01FieldTrait_00_01FieldTrait_1_1Compare_01_4.html
/usr/share/fix8/html/classFIX8_1_1presorted__set_3_01unsigned_01short_00_01FieldTrait_00_01FieldTrait_1_1Compare_01_4.js
/usr/share/fix8/html/classFIX8_1_1reference__wrapper-members.html
/usr/share/fix8/html/classFIX8_1_1reference__wrapper.html
/usr/share/fix8/html/classFIX8_1_1reference__wrapper.js
/usr/share/fix8/html/classFIX8_1_1scoped__ptr-members.html
/usr/share/fix8/html/classFIX8_1_1scoped__ptr.html
/usr/share/fix8/html/classFIX8_1_1scoped__ptr.js
/usr/share/fix8/html/classFIX8_1_1tty__save__state-members.html
/usr/share/fix8/html/classFIX8_1_1tty__save__state.html
/usr/share/fix8/html/classFIX8_1_1tty__save__state.js
/usr/share/fix8/html/classUsageMan-members.html
/usr/share/fix8/html/classUsageMan.html
/usr/share/fix8/html/classUsageMan.js
/usr/share/fix8/html/classXmlElement-members.html
/usr/share/fix8/html/classXmlElement.html
/usr/share/fix8/html/classXmlElement.js
/usr/share/fix8/html/classes.html
/usr/share/fix8/html/classfilestdin-members.html
/usr/share/fix8/html/classfilestdin.html
/usr/share/fix8/html/classfilestdin.js
/usr/share/fix8/html/classgzstreambase-members.html
/usr/share/fix8/html/classgzstreambase.html
/usr/share/fix8/html/classgzstreambase.js
/usr/share/fix8/html/classgzstreambase.png
/usr/share/fix8/html/classgzstreambuf-members.html
/usr/share/fix8/html/classgzstreambuf.html
/usr/share/fix8/html/classgzstreambuf.js
/usr/share/fix8/html/classogzstream-members.html
/usr/share/fix8/html/classogzstream.html
/usr/share/fix8/html/classogzstream.js
/usr/share/fix8/html/classogzstream.png
/usr/share/fix8/html/closed.png
/usr/share/fix8/html/configuration_8cpp.html
/usr/share/fix8/html/configuration_8cpp_source.html
/usr/share/fix8/html/configuration_8hpp.html
/usr/share/fix8/html/configuration_8hpp.js
/usr/share/fix8/html/configuration_8hpp_source.html
/usr/share/fix8/html/connection_8cpp.html
/usr/share/fix8/html/connection_8cpp_source.html
/usr/share/fix8/html/connection_8hpp.html
/usr/share/fix8/html/connection_8hpp.js
/usr/share/fix8/html/connection_8hpp_source.html
/usr/share/fix8/html/consolemenu_8cpp.html
/usr/share/fix8/html/consolemenu_8cpp_source.html
/usr/share/fix8/html/consolemenu_8hpp.html
/usr/share/fix8/html/consolemenu_8hpp.js
/usr/share/fix8/html/consolemenu_8hpp_source.html
/usr/share/fix8/html/doxygen.css
/usr/share/fix8/html/doxygen.png
/usr/share/fix8/html/f8allocator_8hpp.html
/usr/share/fix8/html/f8allocator_8hpp.js
/usr/share/fix8/html/f8allocator_8hpp_source.html
/usr/share/fix8/html/f8c_8cpp.html
/usr/share/fix8/html/f8c_8cpp.js
/usr/share/fix8/html/f8c_8cpp_source.html
/usr/share/fix8/html/f8c_8hpp.html
/usr/share/fix8/html/f8c_8hpp.js
/usr/share/fix8/html/f8c_8hpp_source.html
/usr/share/fix8/html/f8config_8h.html
/usr/share/fix8/html/f8config_8h.js
/usr/share/fix8/html/f8config_8h_source.html
/usr/share/fix8/html/f8cstatic_8hpp.html
/usr/share/fix8/html/f8cstatic_8hpp_source.html
/usr/share/fix8/html/f8cutils_8cpp.html
/usr/share/fix8/html/f8cutils_8cpp.js
/usr/share/fix8/html/f8cutils_8cpp_source.html
/usr/share/fix8/html/f8exception_8hpp.html
/usr/share/fix8/html/f8exception_8hpp.js
/usr/share/fix8/html/f8exception_8hpp_source.html
/usr/share/fix8/html/f8includes_8hpp.html
/usr/share/fix8/html/f8includes_8hpp.js
/usr/share/fix8/html/f8includes_8hpp_source.html
/usr/share/fix8/html/f8precomp_8cpp.html
/usr/share/fix8/html/f8precomp_8cpp.js
/usr/share/fix8/html/f8precomp_8cpp_source.html
/usr/share/fix8/html/f8types_8hpp.html
/usr/share/fix8/html/f8types_8hpp.js
/usr/share/fix8/html/f8types_8hpp_source.html
/usr/share/fix8/html/f8utils_8cpp.html
/usr/share/fix8/html/f8utils_8cpp.js
/usr/share/fix8/html/f8utils_8cpp_source.html
/usr/share/fix8/html/f8utils_8hpp.html
/usr/share/fix8/html/f8utils_8hpp.js
/usr/share/fix8/html/f8utils_8hpp_source.html
/usr/share/fix8/html/field_8cpp.html
/usr/share/fix8/html/field_8cpp.js
/usr/share/fix8/html/field_8cpp_source.html
/usr/share/fix8/html/field_8hpp.html
/usr/share/fix8/html/field_8hpp.js
/usr/share/fix8/html/field_8hpp_source.html
/usr/share/fix8/html/filepersist_8cpp.html
/usr/share/fix8/html/filepersist_8cpp_source.html
/usr/share/fix8/html/files.html
/usr/share/fix8/html/files.js
/usr/share/fix8/html/ftv2blank.png
/usr/share/fix8/html/ftv2doc.png
/usr/share/fix8/html/ftv2folderclosed.png
/usr/share/fix8/html/ftv2folderopen.png
/usr/share/fix8/html/ftv2lastnode.png
/usr/share/fix8/html/ftv2link.png
/usr/share/fix8/html/ftv2mlastnode.png
/usr/share/fix8/html/ftv2mnode.png
/usr/share/fix8/html/ftv2node.png
/usr/share/fix8/html/ftv2plastnode.png
/usr/share/fix8/html/ftv2pnode.png
/usr/share/fix8/html/ftv2splitbar.png
/usr/share/fix8/html/ftv2vertline.png
/usr/share/fix8/html/functions.html
/usr/share/fix8/html/functions_0x61.html
/usr/share/fix8/html/functions_0x62.html
/usr/share/fix8/html/functions_0x63.html
/usr/share/fix8/html/functions_0x64.html
/usr/share/fix8/html/functions_0x65.html
/usr/share/fix8/html/functions_0x66.html
/usr/share/fix8/html/functions_0x67.html
/usr/share/fix8/html/functions_0x68.html
/usr/share/fix8/html/functions_0x69.html
/usr/share/fix8/html/functions_0x6a.html
/usr/share/fix8/html/functions_0x6b.html
/usr/share/fix8/html/functions_0x6c.html
/usr/share/fix8/html/functions_0x6d.html
/usr/share/fix8/html/functions_0x6e.html
/usr/share/fix8/html/functions_0x6f.html
/usr/share/fix8/html/functions_0x70.html
/usr/share/fix8/html/functions_0x71.html
/usr/share/fix8/html/functions_0x72.html
/usr/share/fix8/html/functions_0x73.html
/usr/share/fix8/html/functions_0x74.html
/usr/share/fix8/html/functions_0x75.html
/usr/share/fix8/html/functions_0x76.html
/usr/share/fix8/html/functions_0x77.html
/usr/share/fix8/html/functions_0x78.html
/usr/share/fix8/html/functions_0x7e.html
/usr/share/fix8/html/functions_dup.js
/usr/share/fix8/html/functions_enum.html
/usr/share/fix8/html/functions_eval.html
/usr/share/fix8/html/functions_func.html
/usr/share/fix8/html/functions_func.js
/usr/share/fix8/html/functions_func_0x61.html
/usr/share/fix8/html/functions_func_0x62.html
/usr/share/fix8/html/functions_func_0x63.html
/usr/share/fix8/html/functions_func_0x64.html
/usr/share/fix8/html/functions_func_0x65.html
/usr/share/fix8/html/functions_func_0x66.html
/usr/share/fix8/html/functions_func_0x67.html
/usr/share/fix8/html/functions_func_0x68.html
/usr/share/fix8/html/functions_func_0x69.html
/usr/share/fix8/html/functions_func_0x6a.html
/usr/share/fix8/html/functions_func_0x6b.html
/usr/share/fix8/html/functions_func_0x6c.html
/usr/share/fix8/html/functions_func_0x6d.html
/usr/share/fix8/html/functions_func_0x6e.html
/usr/share/fix8/html/functions_func_0x6f.html
/usr/share/fix8/html/functions_func_0x70.html
/usr/share/fix8/html/functions_func_0x71.html
/usr/share/fix8/html/functions_func_0x72.html
/usr/share/fix8/html/functions_func_0x73.html
/usr/share/fix8/html/functions_func_0x74.html
/usr/share/fix8/html/functions_func_0x75.html
/usr/share/fix8/html/functions_func_0x76.html
/usr/share/fix8/html/functions_func_0x77.html
/usr/share/fix8/html/functions_func_0x78.html
/usr/share/fix8/html/functions_func_0x7e.html
/usr/share/fix8/html/functions_rela.html
/usr/share/fix8/html/functions_type.html
/usr/share/fix8/html/functions_vars.html
/usr/share/fix8/html/functions_vars.js
/usr/share/fix8/html/functions_vars_0x61.html
/usr/share/fix8/html/functions_vars_0x62.html
/usr/share/fix8/html/functions_vars_0x63.html
/usr/share/fix8/html/functions_vars_0x64.html
/usr/share/fix8/html/functions_vars_0x65.html
/usr/share/fix8/html/functions_vars_0x66.html
/usr/share/fix8/html/functions_vars_0x69.html
/usr/share/fix8/html/functions_vars_0x6b.html
/usr/share/fix8/html/functions_vars_0x6c.html
/usr/share/fix8/html/functions_vars_0x6d.html
/usr/share/fix8/html/functions_vars_0x6e.html
/usr/share/fix8/html/functions_vars_0x6f.html
/usr/share/fix8/html/functions_vars_0x70.html
/usr/share/fix8/html/functions_vars_0x72.html
/usr/share/fix8/html/functions_vars_0x73.html
/usr/share/fix8/html/functions_vars_0x74.html
/usr/share/fix8/html/functions_vars_0x76.html
/usr/share/fix8/html/functions_vars_0x78.html
/usr/share/fix8/html/globals.html
/usr/share/fix8/html/globals_0x62.html
/usr/share/fix8/html/globals_0x63.html
/usr/share/fix8/html/globals_0x64.html
/usr/share/fix8/html/globals_0x65.html
/usr/share/fix8/html/globals_0x66.html
/usr/share/fix8/html/globals_0x67.html
/usr/share/fix8/html/globals_0x68.html
/usr/share/fix8/html/globals_0x69.html
/usr/share/fix8/html/globals_0x6c.html
/usr/share/fix8/html/globals_0x6d.html
/usr/share/fix8/html/globals_0x6f.html
/usr/share/fix8/html/globals_0x70.html
/usr/share/fix8/html/globals_0x71.html
/usr/share/fix8/html/globals_0x72.html
/usr/share/fix8/html/globals_0x73.html
/usr/share/fix8/html/globals_0x74.html
/usr/share/fix8/html/globals_0x76.html
/usr/share/fix8/html/globals_defs.html
/usr/share/fix8/html/globals_dup.js
/usr/share/fix8/html/globals_func.html
/usr/share/fix8/html/globals_type.html
/usr/share/fix8/html/globals_vars.html
/usr/share/fix8/html/gzstream_8cpp.html
/usr/share/fix8/html/gzstream_8cpp_source.html
/usr/share/fix8/html/gzstream_8hpp.html
/usr/share/fix8/html/gzstream_8hpp_source.html
/usr/share/fix8/html/harness_8cpp.html
/usr/share/fix8/html/harness_8cpp.js
/usr/share/fix8/html/harness_8cpp_source.html
/usr/share/fix8/html/hfprint_8cpp.html
/usr/share/fix8/html/hfprint_8cpp.js
/usr/share/fix8/html/hfprint_8cpp_source.html
/usr/share/fix8/html/hftest_8cpp.html
/usr/share/fix8/html/hftest_8cpp.js
/usr/share/fix8/html/hftest_8cpp_source.html
/usr/share/fix8/html/hftest_8hpp.html
/usr/share/fix8/html/hftest_8hpp_source.html
/usr/share/fix8/html/hierarchy.html
/usr/share/fix8/html/hierarchy.js
/usr/share/fix8/html/index.html
/usr/share/fix8/html/jquery.js
/usr/share/fix8/html/logger_8cpp.html
/usr/share/fix8/html/logger_8cpp_source.html
/usr/share/fix8/html/logger_8hpp.html
/usr/share/fix8/html/logger_8hpp.js
/usr/share/fix8/html/logger_8hpp_source.html
/usr/share/fix8/html/mainpage_8doxygen.html
/usr/share/fix8/html/mainpage_8doxygen_source.html
/usr/share/fix8/html/memory_8cpp.html
/usr/share/fix8/html/memory_8cpp.js
/usr/share/fix8/html/memory_8cpp_source.html
/usr/share/fix8/html/memory_8hpp.html
/usr/share/fix8/html/memory_8hpp.js
/usr/share/fix8/html/memory_8hpp_source.html
/usr/share/fix8/html/message_8cpp.html
/usr/share/fix8/html/message_8cpp_source.html
/usr/share/fix8/html/message_8hpp.html
/usr/share/fix8/html/message_8hpp.js
/usr/share/fix8/html/message_8hpp_source.html
/usr/share/fix8/html/myfix_8cpp.html
/usr/share/fix8/html/myfix_8cpp.js
/usr/share/fix8/html/myfix_8cpp_source.html
/usr/share/fix8/html/myfix_8hpp.html
/usr/share/fix8/html/myfix_8hpp_source.html
/usr/share/fix8/html/myfix__custom_8hpp.html
/usr/share/fix8/html/myfix__custom_8hpp_source.html
/usr/share/fix8/html/myprint_8cpp.html
/usr/share/fix8/html/myprint_8cpp.js
/usr/share/fix8/html/myprint_8cpp_source.html
/usr/share/fix8/html/namespaceFIX8.html
/usr/share/fix8/html/namespaceFIX8.js
/usr/share/fix8/html/namespaceFIX8_1_1TEX.html
/usr/share/fix8/html/namespaceFIX8_1_1TEX.js
/usr/share/fix8/html/namespacemembers.html
/usr/share/fix8/html/namespacemembers_enum.html
/usr/share/fix8/html/namespacemembers_eval.html
/usr/share/fix8/html/namespacemembers_func.html
/usr/share/fix8/html/namespacemembers_type.html
/usr/share/fix8/html/namespacemembers_vars.html
/usr/share/fix8/html/namespaces.html
/usr/share/fix8/html/namespaces.js
/usr/share/fix8/html/nav_f.png
/usr/share/fix8/html/nav_h.png
/usr/share/fix8/html/navtree.css
/usr/share/fix8/html/navtree.js
/usr/share/fix8/html/navtreeindex.js
/usr/share/fix8/html/open.png
/usr/share/fix8/html/persist_8cpp.html
/usr/share/fix8/html/persist_8cpp.js
/usr/share/fix8/html/persist_8cpp_source.html
/usr/share/fix8/html/persist_8hpp.html
/usr/share/fix8/html/persist_8hpp.js
/usr/share/fix8/html/persist_8hpp_source.html
/usr/share/fix8/html/popen_8c.html
/usr/share/fix8/html/popen_8c.js
/usr/share/fix8/html/popen_8c_source.html
/usr/share/fix8/html/resize.js
/usr/share/fix8/html/search/all_5f.html
/usr/share/fix8/html/search/all_5f.js
/usr/share/fix8/html/search/all_61.html
/usr/share/fix8/html/search/all_61.js
/usr/share/fix8/html/search/all_62.html
/usr/share/fix8/html/search/all_62.js
/usr/share/fix8/html/search/all_63.html
/usr/share/fix8/html/search/all_63.js
/usr/share/fix8/html/search/all_64.html
/usr/share/fix8/html/search/all_64.js
/usr/share/fix8/html/search/all_65.html
/usr/share/fix8/html/search/all_65.js
/usr/share/fix8/html/search/all_66.html
/usr/share/fix8/html/search/all_66.js
/usr/share/fix8/html/search/all_67.html
/usr/share/fix8/html/search/all_67.js
/usr/share/fix8/html/search/all_68.html
/usr/share/fix8/html/search/all_68.js
/usr/share/fix8/html/search/all_69.html
/usr/share/fix8/html/search/all_69.js
/usr/share/fix8/html/search/all_6a.html
/usr/share/fix8/html/search/all_6a.js
/usr/share/fix8/html/search/all_6b.html
/usr/share/fix8/html/search/all_6b.js
/usr/share/fix8/html/search/all_6c.html
/usr/share/fix8/html/search/all_6c.js
/usr/share/fix8/html/search/all_6d.html
/usr/share/fix8/html/search/all_6d.js
/usr/share/fix8/html/search/all_6e.html
/usr/share/fix8/html/search/all_6e.js
/usr/share/fix8/html/search/all_6f.html
/usr/share/fix8/html/search/all_6f.js
/usr/share/fix8/html/search/all_70.html
/usr/share/fix8/html/search/all_70.js
/usr/share/fix8/html/search/all_71.html
/usr/share/fix8/html/search/all_71.js
/usr/share/fix8/html/search/all_72.html
/usr/share/fix8/html/search/all_72.js
/usr/share/fix8/html/search/all_73.html
/usr/share/fix8/html/search/all_73.js
/usr/share/fix8/html/search/all_74.html
/usr/share/fix8/html/search/all_74.js
/usr/share/fix8/html/search/all_75.html
/usr/share/fix8/html/search/all_75.js
/usr/share/fix8/html/search/all_76.html
/usr/share/fix8/html/search/all_76.js
/usr/share/fix8/html/search/all_77.html
/usr/share/fix8/html/search/all_77.js
/usr/share/fix8/html/search/all_78.html
/usr/share/fix8/html/search/all_78.js
/usr/share/fix8/html/search/all_7e.html
/usr/share/fix8/html/search/all_7e.js
/usr/share/fix8/html/search/classes_5f.html
/usr/share/fix8/html/search/classes_5f.js
/usr/share/fix8/html/search/classes_61.html
/usr/share/fix8/html/search/classes_61.js
/usr/share/fix8/html/search/classes_62.html
/usr/share/fix8/html/search/classes_62.js
/usr/share/fix8/html/search/classes_63.html
/usr/share/fix8/html/search/classes_63.js
/usr/share/fix8/html/search/classes_64.html
/usr/share/fix8/html/search/classes_64.js
/usr/share/fix8/html/search/classes_65.html
/usr/share/fix8/html/search/classes_65.js
/usr/share/fix8/html/search/classes_66.html
/usr/share/fix8/html/search/classes_66.js
/usr/share/fix8/html/search/classes_67.html
/usr/share/fix8/html/search/classes_67.js
/usr/share/fix8/html/search/classes_69.html
/usr/share/fix8/html/search/classes_69.js
/usr/share/fix8/html/search/classes_6b.html
/usr/share/fix8/html/search/classes_6b.js
/usr/share/fix8/html/search/classes_6c.html
/usr/share/fix8/html/search/classes_6c.js
/usr/share/fix8/html/search/classes_6d.html
/usr/share/fix8/html/search/classes_6d.js
/usr/share/fix8/html/search/classes_6f.html
/usr/share/fix8/html/search/classes_6f.js
/usr/share/fix8/html/search/classes_70.html
/usr/share/fix8/html/search/classes_70.js
/usr/share/fix8/html/search/classes_72.html
/usr/share/fix8/html/search/classes_72.js
/usr/share/fix8/html/search/classes_73.html
/usr/share/fix8/html/search/classes_73.js
/usr/share/fix8/html/search/classes_74.html
/usr/share/fix8/html/search/classes_74.js
/usr/share/fix8/html/search/classes_75.html
/usr/share/fix8/html/search/classes_75.js
/usr/share/fix8/html/search/classes_78.html
/usr/share/fix8/html/search/classes_78.js
/usr/share/fix8/html/search/close.png
/usr/share/fix8/html/search/defines_5f.html
/usr/share/fix8/html/search/defines_5f.js
/usr/share/fix8/html/search/defines_63.html
/usr/share/fix8/html/search/defines_63.js
/usr/share/fix8/html/search/defines_68.html
/usr/share/fix8/html/search/defines_68.js
/usr/share/fix8/html/search/defines_69.html
/usr/share/fix8/html/search/defines_69.js
/usr/share/fix8/html/search/defines_6c.html
/usr/share/fix8/html/search/defines_6c.js
/usr/share/fix8/html/search/defines_6d.html
/usr/share/fix8/html/search/defines_6d.js
/usr/share/fix8/html/search/defines_70.html
/usr/share/fix8/html/search/defines_70.js
/usr/share/fix8/html/search/defines_72.html
/usr/share/fix8/html/search/defines_72.js
/usr/share/fix8/html/search/defines_73.html
/usr/share/fix8/html/search/defines_73.js
/usr/share/fix8/html/search/defines_74.html
/usr/share/fix8/html/search/defines_74.js
/usr/share/fix8/html/search/defines_76.html
/usr/share/fix8/html/search/defines_76.js
/usr/share/fix8/html/search/enums_63.html
/usr/share/fix8/html/search/enums_63.js
/usr/share/fix8/html/search/enums_66.html
/usr/share/fix8/html/search/enums_66.js
/usr/share/fix8/html/search/enums_6c.html
/usr/share/fix8/html/search/enums_6c.js
/usr/share/fix8/html/search/enums_6d.html
/usr/share/fix8/html/search/enums_6d.js
/usr/share/fix8/html/search/enums_6f.html
/usr/share/fix8/html/search/enums_6f.js
/usr/share/fix8/html/search/enums_72.html
/usr/share/fix8/html/search/enums_72.js
/usr/share/fix8/html/search/enums_73.html
/usr/share/fix8/html/search/enums_73.js
/usr/share/fix8/html/search/enums_74.html
/usr/share/fix8/html/search/enums_74.js
/usr/share/fix8/html/search/enumvalues_5f.html
/usr/share/fix8/html/search/enumvalues_5f.js
/usr/share/fix8/html/search/enumvalues_61.html
/usr/share/fix8/html/search/enumvalues_61.js
/usr/share/fix8/html/search/enumvalues_62.html
/usr/share/fix8/html/search/enumvalues_62.js
/usr/share/fix8/html/search/enumvalues_63.html
/usr/share/fix8/html/search/enumvalues_63.js
/usr/share/fix8/html/search/enumvalues_64.html
/usr/share/fix8/html/search/enumvalues_64.js
/usr/share/fix8/html/search/enumvalues_66.html
/usr/share/fix8/html/search/enumvalues_66.js
/usr/share/fix8/html/search/enumvalues_67.html
/usr/share/fix8/html/search/enumvalues_67.js
/usr/share/fix8/html/search/enumvalues_6d.html
/usr/share/fix8/html/search/enumvalues_6d.js
/usr/share/fix8/html/search/enumvalues_6e.html
/usr/share/fix8/html/search/enumvalues_6e.js
/usr/share/fix8/html/search/enumvalues_70.html
/usr/share/fix8/html/search/enumvalues_70.js
/usr/share/fix8/html/search/enumvalues_72.html
/usr/share/fix8/html/search/enumvalues_72.js
/usr/share/fix8/html/search/enumvalues_73.html
/usr/share/fix8/html/search/enumvalues_73.js
/usr/share/fix8/html/search/enumvalues_74.html
/usr/share/fix8/html/search/enumvalues_74.js
/usr/share/fix8/html/search/enumvalues_76.html
/usr/share/fix8/html/search/enumvalues_76.js
/usr/share/fix8/html/search/files_63.html
/usr/share/fix8/html/search/files_63.js
/usr/share/fix8/html/search/files_66.html
/usr/share/fix8/html/search/files_66.js
/usr/share/fix8/html/search/files_67.html
/usr/share/fix8/html/search/files_67.js
/usr/share/fix8/html/search/files_68.html
/usr/share/fix8/html/search/files_68.js
/usr/share/fix8/html/search/files_6c.html
/usr/share/fix8/html/search/files_6c.js
/usr/share/fix8/html/search/files_6d.html
/usr/share/fix8/html/search/files_6d.js
/usr/share/fix8/html/search/files_70.html
/usr/share/fix8/html/search/files_70.js
/usr/share/fix8/html/search/files_73.html
/usr/share/fix8/html/search/files_73.js
/usr/share/fix8/html/search/files_74.html
/usr/share/fix8/html/search/files_74.js
/usr/share/fix8/html/search/files_75.html
/usr/share/fix8/html/search/files_75.js
/usr/share/fix8/html/search/files_78.html
/usr/share/fix8/html/search/files_78.js
/usr/share/fix8/html/search/functions_5f.html
/usr/share/fix8/html/search/functions_5f.js
/usr/share/fix8/html/search/functions_61.html
/usr/share/fix8/html/search/functions_61.js
/usr/share/fix8/html/search/functions_62.html
/usr/share/fix8/html/search/functions_62.js
/usr/share/fix8/html/search/functions_63.html
/usr/share/fix8/html/search/functions_63.js
/usr/share/fix8/html/search/functions_64.html
/usr/share/fix8/html/search/functions_64.js
/usr/share/fix8/html/search/functions_65.html
/usr/share/fix8/html/search/functions_65.js
/usr/share/fix8/html/search/functions_66.html
/usr/share/fix8/html/search/functions_66.js
/usr/share/fix8/html/search/functions_67.html
/usr/share/fix8/html/search/functions_67.js
/usr/share/fix8/html/search/functions_68.html
/usr/share/fix8/html/search/functions_68.js
/usr/share/fix8/html/search/functions_69.html
/usr/share/fix8/html/search/functions_69.js
/usr/share/fix8/html/search/functions_6a.html
/usr/share/fix8/html/search/functions_6a.js
/usr/share/fix8/html/search/functions_6b.html
/usr/share/fix8/html/search/functions_6b.js
/usr/share/fix8/html/search/functions_6c.html
/usr/share/fix8/html/search/functions_6c.js
/usr/share/fix8/html/search/functions_6d.html
/usr/share/fix8/html/search/functions_6d.js
/usr/share/fix8/html/search/functions_6e.html
/usr/share/fix8/html/search/functions_6e.js
/usr/share/fix8/html/search/functions_6f.html
/usr/share/fix8/html/search/functions_6f.js
/usr/share/fix8/html/search/functions_70.html
/usr/share/fix8/html/search/functions_70.js
/usr/share/fix8/html/search/functions_71.html
/usr/share/fix8/html/search/functions_71.js
/usr/share/fix8/html/search/functions_72.html
/usr/share/fix8/html/search/functions_72.js
/usr/share/fix8/html/search/functions_73.html
/usr/share/fix8/html/search/functions_73.js
/usr/share/fix8/html/search/functions_74.html
/usr/share/fix8/html/search/functions_74.js
/usr/share/fix8/html/search/functions_75.html
/usr/share/fix8/html/search/functions_75.js
/usr/share/fix8/html/search/functions_76.html
/usr/share/fix8/html/search/functions_76.js
/usr/share/fix8/html/search/functions_77.html
/usr/share/fix8/html/search/functions_77.js
/usr/share/fix8/html/search/functions_78.html
/usr/share/fix8/html/search/functions_78.js
/usr/share/fix8/html/search/functions_7e.html
/usr/share/fix8/html/search/functions_7e.js
/usr/share/fix8/html/search/mag_sel.png
/usr/share/fix8/html/search/namespaces_66.html
/usr/share/fix8/html/search/namespaces_66.js
/usr/share/fix8/html/search/nomatches.html
/usr/share/fix8/html/search/related_6d.html
/usr/share/fix8/html/search/related_6d.js
/usr/share/fix8/html/search/related_6f.html
/usr/share/fix8/html/search/related_6f.js
/usr/share/fix8/html/search/related_72.html
/usr/share/fix8/html/search/related_72.js
/usr/share/fix8/html/search/related_73.html
/usr/share/fix8/html/search/related_73.js
/usr/share/fix8/html/search/related_74.html
/usr/share/fix8/html/search/related_74.js
/usr/share/fix8/html/search/search.css
/usr/share/fix8/html/search/search.js
/usr/share/fix8/html/search/search_l.png
/usr/share/fix8/html/search/search_m.png
/usr/share/fix8/html/search/search_r.png
/usr/share/fix8/html/search/typedefs_61.html
/usr/share/fix8/html/search/typedefs_61.js
/usr/share/fix8/html/search/typedefs_62.html
/usr/share/fix8/html/search/typedefs_62.js
/usr/share/fix8/html/search/typedefs_63.html
/usr/share/fix8/html/search/typedefs_63.js
/usr/share/fix8/html/search/typedefs_64.html
/usr/share/fix8/html/search/typedefs_64.js
/usr/share/fix8/html/search/typedefs_65.html
/usr/share/fix8/html/search/typedefs_65.js
/usr/share/fix8/html/search/typedefs_66.html
/usr/share/fix8/html/search/typedefs_66.js
/usr/share/fix8/html/search/typedefs_67.html
/usr/share/fix8/html/search/typedefs_67.js
/usr/share/fix8/html/search/typedefs_68.html
/usr/share/fix8/html/search/typedefs_68.js
/usr/share/fix8/html/search/typedefs_69.html
/usr/share/fix8/html/search/typedefs_69.js
/usr/share/fix8/html/search/typedefs_6c.html
/usr/share/fix8/html/search/typedefs_6c.js
/usr/share/fix8/html/search/typedefs_6d.html
/usr/share/fix8/html/search/typedefs_6d.js
/usr/share/fix8/html/search/typedefs_6e.html
/usr/share/fix8/html/search/typedefs_6e.js
/usr/share/fix8/html/search/typedefs_6f.html
/usr/share/fix8/html/search/typedefs_6f.js
/usr/share/fix8/html/search/typedefs_70.html
/usr/share/fix8/html/search/typedefs_70.js
/usr/share/fix8/html/search/typedefs_71.html
/usr/share/fix8/html/search/typedefs_71.js
/usr/share/fix8/html/search/typedefs_72.html
/usr/share/fix8/html/search/typedefs_72.js
/usr/share/fix8/html/search/typedefs_73.html
/usr/share/fix8/html/search/typedefs_73.js
/usr/share/fix8/html/search/typedefs_74.html
/usr/share/fix8/html/search/typedefs_74.js
/usr/share/fix8/html/search/typedefs_75.html
/usr/share/fix8/html/search/typedefs_75.js
/usr/share/fix8/html/search/typedefs_76.html
/usr/share/fix8/html/search/typedefs_76.js
/usr/share/fix8/html/search/typedefs_78.html
/usr/share/fix8/html/search/typedefs_78.js
/usr/share/fix8/html/search/variables_5f.html
/usr/share/fix8/html/search/variables_5f.js
/usr/share/fix8/html/search/variables_61.html
/usr/share/fix8/html/search/variables_61.js
/usr/share/fix8/html/search/variables_62.html
/usr/share/fix8/html/search/variables_62.js
/usr/share/fix8/html/search/variables_63.html
/usr/share/fix8/html/search/variables_63.js
/usr/share/fix8/html/search/variables_64.html
/usr/share/fix8/html/search/variables_64.js
/usr/share/fix8/html/search/variables_65.html
/usr/share/fix8/html/search/variables_65.js
/usr/share/fix8/html/search/variables_66.html
/usr/share/fix8/html/search/variables_66.js
/usr/share/fix8/html/search/variables_67.html
/usr/share/fix8/html/search/variables_67.js
/usr/share/fix8/html/search/variables_69.html
/usr/share/fix8/html/search/variables_69.js
/usr/share/fix8/html/search/variables_6b.html
/usr/share/fix8/html/search/variables_6b.js
/usr/share/fix8/html/search/variables_6c.html
/usr/share/fix8/html/search/variables_6c.js
/usr/share/fix8/html/search/variables_6d.html
/usr/share/fix8/html/search/variables_6d.js
/usr/share/fix8/html/search/variables_6e.html
/usr/share/fix8/html/search/variables_6e.js
/usr/share/fix8/html/search/variables_6f.html
/usr/share/fix8/html/search/variables_6f.js
/usr/share/fix8/html/search/variables_70.html
/usr/share/fix8/html/search/variables_70.js
/usr/share/fix8/html/search/variables_72.html
/usr/share/fix8/html/search/variables_72.js
/usr/share/fix8/html/search/variables_73.html
/usr/share/fix8/html/search/variables_73.js
/usr/share/fix8/html/search/variables_74.html
/usr/share/fix8/html/search/variables_74.js
/usr/share/fix8/html/search/variables_76.html
/usr/share/fix8/html/search/variables_76.js
/usr/share/fix8/html/search/variables_78.html
/usr/share/fix8/html/search/variables_78.js
/usr/share/fix8/html/session_8cpp.html
/usr/share/fix8/html/session_8cpp_source.html
/usr/share/fix8/html/session_8hpp.html
/usr/share/fix8/html/session_8hpp.js
/usr/share/fix8/html/session_8hpp_source.html
/usr/share/fix8/html/sessionwrapper_8hpp.html
/usr/share/fix8/html/sessionwrapper_8hpp.js
/usr/share/fix8/html/sessionwrapper_8hpp_source.html
/usr/share/fix8/html/structFIX8_1_1BDBPersister_1_1KeyDataBuffer-members.html
/usr/share/fix8/html/structFIX8_1_1BDBPersister_1_1KeyDataBuffer.html
/usr/share/fix8/html/structFIX8_1_1BDBPersister_1_1KeyDataBuffer.js
/usr/share/fix8/html/structFIX8_1_1BDBPersister_1_1KeyDataPair-members.html
/usr/share/fix8/html/structFIX8_1_1BDBPersister_1_1KeyDataPair.html
/usr/share/fix8/html/structFIX8_1_1BDBPersister_1_1KeyDataPair.js
/usr/share/fix8/html/structFIX8_1_1BadCheckSum-members.html
/usr/share/fix8/html/structFIX8_1_1BadCheckSum.html
/usr/share/fix8/html/structFIX8_1_1BadCheckSum.js
/usr/share/fix8/html/structFIX8_1_1BadCheckSum.png
/usr/share/fix8/html/structFIX8_1_1BadCompidId-members.html
/usr/share/fix8/html/structFIX8_1_1BadCompidId.html
/usr/share/fix8/html/structFIX8_1_1BadCompidId.js
/usr/share/fix8/html/structFIX8_1_1BadCompidId.png
/usr/share/fix8/html/structFIX8_1_1BadSendingTime-members.html
/usr/share/fix8/html/structFIX8_1_1BadSendingTime.html
/usr/share/fix8/html/structFIX8_1_1BadSendingTime.js
/usr/share/fix8/html/structFIX8_1_1BadSendingTime.png
/usr/share/fix8/html/structFIX8_1_1BaseAllocator-members.html
/usr/share/fix8/html/structFIX8_1_1BaseAllocator.html
/usr/share/fix8/html/structFIX8_1_1BaseAllocator.js
/usr/share/fix8/html/structFIX8_1_1BaseAllocator.png
/usr/share/fix8/html/structFIX8_1_1BaseEntry-members.html
/usr/share/fix8/html/structFIX8_1_1BaseEntry.html
/usr/share/fix8/html/structFIX8_1_1BaseEntry.js
/usr/share/fix8/html/structFIX8_1_1BaseMsgEntry-members.html
/usr/share/fix8/html/structFIX8_1_1BaseMsgEntry.html
/usr/share/fix8/html/structFIX8_1_1BaseMsgEntry.js
/usr/share/fix8/html/structFIX8_1_1CharRealm-members.html
/usr/share/fix8/html/structFIX8_1_1CharRealm.html
/usr/share/fix8/html/structFIX8_1_1CharRealm.js
/usr/share/fix8/html/structFIX8_1_1CharRealm.png
/usr/share/fix8/html/structFIX8_1_1Ctxt-members.html
/usr/share/fix8/html/structFIX8_1_1Ctxt.html
/usr/share/fix8/html/structFIX8_1_1Ctxt.js
/usr/share/fix8/html/structFIX8_1_1Delete1stPairObject-members.html
/usr/share/fix8/html/structFIX8_1_1Delete1stPairObject.html
/usr/share/fix8/html/structFIX8_1_1Delete1stPairObject.js
/usr/share/fix8/html/structFIX8_1_1Delete2ndPairObject-members.html
/usr/share/fix8/html/structFIX8_1_1Delete2ndPairObject.html
/usr/share/fix8/html/structFIX8_1_1Delete2ndPairObject.js
/usr/share/fix8/html/structFIX8_1_1DeleteArrayObject-members.html
/usr/share/fix8/html/structFIX8_1_1DeleteArrayObject.html
/usr/share/fix8/html/structFIX8_1_1DeleteArrayObject.js
/usr/share/fix8/html/structFIX8_1_1DeleteObject-members.html
/usr/share/fix8/html/structFIX8_1_1DeleteObject.html
/usr/share/fix8/html/structFIX8_1_1DeleteObject.js
/usr/share/fix8/html/structFIX8_1_1DuplicateField-members.html
/usr/share/fix8/html/structFIX8_1_1DuplicateField.html
/usr/share/fix8/html/structFIX8_1_1DuplicateField.js
/usr/share/fix8/html/structFIX8_1_1DuplicateField.png
/usr/share/fix8/html/structFIX8_1_1EnumType-members.html
/usr/share/fix8/html/structFIX8_1_1EnumType.html
/usr/share/fix8/html/structFIX8_1_1F8MetaCntx-members.html
/usr/share/fix8/html/structFIX8_1_1F8MetaCntx.html
/usr/share/fix8/html/structFIX8_1_1F8MetaCntx.js
/usr/share/fix8/html/structFIX8_1_1FieldSpec-members.html
/usr/share/fix8/html/structFIX8_1_1FieldSpec.html
/usr/share/fix8/html/structFIX8_1_1FieldSpec.js
/usr/share/fix8/html/structFIX8_1_1FieldTrait-members.html
/usr/share/fix8/html/structFIX8_1_1FieldTrait.html
/usr/share/fix8/html/structFIX8_1_1FieldTrait.js
/usr/share/fix8/html/structFIX8_1_1FieldTrait_1_1Compare-members.html
/usr/share/fix8/html/structFIX8_1_1FieldTrait_1_1Compare.html
/usr/share/fix8/html/structFIX8_1_1FieldTrait_1_1Compare.js
/usr/share/fix8/html/structFIX8_1_1FieldTrait_1_1PosCompare-members.html
/usr/share/fix8/html/structFIX8_1_1FieldTrait_1_1PosCompare.html
/usr/share/fix8/html/structFIX8_1_1FieldTrait_1_1PosCompare.js
/usr/share/fix8/html/structFIX8_1_1FieldTrait__Hash__Array-members.html
/usr/share/fix8/html/structFIX8_1_1FieldTrait__Hash__Array.html
/usr/share/fix8/html/structFIX8_1_1FieldTrait__Hash__Array.js
/usr/share/fix8/html/structFIX8_1_1FilePersister_1_1IPrec-members.html
/usr/share/fix8/html/structFIX8_1_1FilePersister_1_1IPrec.html
/usr/share/fix8/html/structFIX8_1_1FilePersister_1_1IPrec.js
/usr/share/fix8/html/structFIX8_1_1FilePersister_1_1Prec-members.html
/usr/share/fix8/html/structFIX8_1_1FilePersister_1_1Prec.html
/usr/share/fix8/html/structFIX8_1_1FilePersister_1_1Prec.js
/usr/share/fix8/html/structFIX8_1_1FreelistFull-members.html
/usr/share/fix8/html/structFIX8_1_1FreelistFull.html
/usr/share/fix8/html/structFIX8_1_1FreelistFull.js
/usr/share/fix8/html/structFIX8_1_1FreelistFull.png
/usr/share/fix8/html/structFIX8_1_1GeneratedTable_1_1Pair-members.html
/usr/share/fix8/html/structFIX8_1_1GeneratedTable_1_1Pair.html
/usr/share/fix8/html/structFIX8_1_1GeneratedTable_1_1Pair.js
/usr/share/fix8/html/structFIX8_1_1GeneratedTable_1_1Pair_1_1Less-members.html
/usr/share/fix8/html/structFIX8_1_1GeneratedTable_1_1Pair_1_1Less.html
/usr/share/fix8/html/structFIX8_1_1GeneratedTable_1_1Pair_1_1Less.js
/usr/share/fix8/html/structFIX8_1_1IllegalMessage-members.html
/usr/share/fix8/html/structFIX8_1_1IllegalMessage.html
/usr/share/fix8/html/structFIX8_1_1IllegalMessage.js
/usr/share/fix8/html/structFIX8_1_1IllegalMessage.png
/usr/share/fix8/html/structFIX8_1_1InvalidBodyLength-members.html
/usr/share/fix8/html/structFIX8_1_1InvalidBodyLength.html
/usr/share/fix8/html/structFIX8_1_1InvalidBodyLength.js
/usr/share/fix8/html/structFIX8_1_1InvalidBodyLength.png
/usr/share/fix8/html/structFIX8_1_1InvalidConfiguration-members.html
/usr/share/fix8/html/structFIX8_1_1InvalidConfiguration.html
/usr/share/fix8/html/structFIX8_1_1InvalidConfiguration.js
/usr/share/fix8/html/structFIX8_1_1InvalidConfiguration.png
/usr/share/fix8/html/structFIX8_1_1InvalidDomainValue-members.html
/usr/share/fix8/html/structFIX8_1_1InvalidDomainValue.html
/usr/share/fix8/html/structFIX8_1_1InvalidDomainValue.js
/usr/share/fix8/html/structFIX8_1_1InvalidDomainValue.png
/usr/share/fix8/html/structFIX8_1_1InvalidField-members.html
/usr/share/fix8/html/structFIX8_1_1InvalidField.html
/usr/share/fix8/html/structFIX8_1_1InvalidField.js
/usr/share/fix8/html/structFIX8_1_1InvalidField.png
/usr/share/fix8/html/structFIX8_1_1InvalidMemoryPtr-members.html
/usr/share/fix8/html/structFIX8_1_1InvalidMemoryPtr.html
/usr/share/fix8/html/structFIX8_1_1InvalidMemoryPtr.js
/usr/share/fix8/html/structFIX8_1_1InvalidMemoryPtr.png
/usr/share/fix8/html/structFIX8_1_1InvalidMessage-members.html
/usr/share/fix8/html/structFIX8_1_1InvalidMessage.html
/usr/share/fix8/html/structFIX8_1_1InvalidMessage.js
/usr/share/fix8/html/structFIX8_1_1InvalidMessage.png
/usr/share/fix8/html/structFIX8_1_1InvalidMetadata-members.html
/usr/share/fix8/html/structFIX8_1_1InvalidMetadata.html
/usr/share/fix8/html/structFIX8_1_1InvalidMetadata.js
/usr/share/fix8/html/structFIX8_1_1InvalidMetadata.png
/usr/share/fix8/html/structFIX8_1_1InvalidMsgSequence-members.html
/usr/share/fix8/html/structFIX8_1_1InvalidMsgSequence.html
/usr/share/fix8/html/structFIX8_1_1InvalidMsgSequence.js
/usr/share/fix8/html/structFIX8_1_1InvalidMsgSequence.png
/usr/share/fix8/html/structFIX8_1_1InvalidRepeatingGroup-members.html
/usr/share/fix8/html/structFIX8_1_1InvalidRepeatingGroup.html
/usr/share/fix8/html/structFIX8_1_1InvalidRepeatingGroup.js
/usr/share/fix8/html/structFIX8_1_1InvalidRepeatingGroup.png
/usr/share/fix8/html/structFIX8_1_1InvalidVersion-members.html
/usr/share/fix8/html/structFIX8_1_1InvalidVersion.html
/usr/share/fix8/html/structFIX8_1_1InvalidVersion.js
/usr/share/fix8/html/structFIX8_1_1InvalidVersion.png
/usr/share/fix8/html/structFIX8_1_1Logger_1_1LogElement-members.html
/usr/share/fix8/html/structFIX8_1_1Logger_1_1LogElement.html
/usr/share/fix8/html/structFIX8_1_1Logger_1_1LogElement.js
/usr/share/fix8/html/structFIX8_1_1LoginParameters-members.html
/usr/share/fix8/html/structFIX8_1_1LoginParameters.html
/usr/share/fix8/html/structFIX8_1_1LoginParameters.js
/usr/share/fix8/html/structFIX8_1_1MessageSpec-members.html
/usr/share/fix8/html/structFIX8_1_1MessageSpec.html
/usr/share/fix8/html/structFIX8_1_1MessageSpec.js
/usr/share/fix8/html/structFIX8_1_1MissingMandatoryField-members.html
/usr/share/fix8/html/structFIX8_1_1MissingMandatoryField.html
/usr/share/fix8/html/structFIX8_1_1MissingMandatoryField.js
/usr/share/fix8/html/structFIX8_1_1MissingMandatoryField.png
/usr/share/fix8/html/structFIX8_1_1MissingMessageComponent-members.html
/usr/share/fix8/html/structFIX8_1_1MissingMessageComponent.html
/usr/share/fix8/html/structFIX8_1_1MissingMessageComponent.js
/usr/share/fix8/html/structFIX8_1_1MissingMessageComponent.png
/usr/share/fix8/html/structFIX8_1_1MissingRepeatingGroupField-members.html
/usr/share/fix8/html/structFIX8_1_1MissingRepeatingGroupField.html
/usr/share/fix8/html/structFIX8_1_1MissingRepeatingGroupField.js
/usr/share/fix8/html/structFIX8_1_1MissingRepeatingGroupField.png
/usr/share/fix8/html/structFIX8_1_1MsgSequenceTooLow-members.html
/usr/share/fix8/html/structFIX8_1_1MsgSequenceTooLow.html
/usr/share/fix8/html/structFIX8_1_1MsgSequenceTooLow.js
/usr/share/fix8/html/structFIX8_1_1MsgSequenceTooLow.png
/usr/share/fix8/html/structFIX8_1_1PeerResetConnection-members.html
/usr/share/fix8/html/structFIX8_1_1PeerResetConnection.html
/usr/share/fix8/html/structFIX8_1_1PeerResetConnection.js
/usr/share/fix8/html/structFIX8_1_1PeerResetConnection.png
/usr/share/fix8/html/structFIX8_1_1RealmBase-members.html
/usr/share/fix8/html/structFIX8_1_1RealmBase.html
/usr/share/fix8/html/structFIX8_1_1RealmBase.js
/usr/share/fix8/html/structFIX8_1_1RealmObject_1_1less-members.html
/usr/share/fix8/html/structFIX8_1_1RealmObject_1_1less.html
/usr/share/fix8/html/structFIX8_1_1RealmObject_1_1less.js
/usr/share/fix8/html/structFIX8_1_1SessionConfig-members.html
/usr/share/fix8/html/structFIX8_1_1SessionConfig.html
/usr/share/fix8/html/structFIX8_1_1SessionConfig.js
/usr/share/fix8/html/structFIX8_1_1SessionConfig.png
/usr/share/fix8/html/structFIX8_1_1Session_1_1RetransmissionContext-members.html
/usr/share/fix8/html/structFIX8_1_1Session_1_1RetransmissionContext.html
/usr/share/fix8/html/structFIX8_1_1Session_1_1RetransmissionContext.js
/usr/share/fix8/html/structFIX8_1_1States-members.html
/usr/share/fix8/html/structFIX8_1_1States.html
/usr/share/fix8/html/structFIX8_1_1States.js
/usr/share/fix8/html/structFIX8_1_1StaticTable-members.html
/usr/share/fix8/html/structFIX8_1_1StaticTable.html
/usr/share/fix8/html/structFIX8_1_1StaticTable.js
/usr/share/fix8/html/structFIX8_1_1StringLessThanNoCase-members.html
/usr/share/fix8/html/structFIX8_1_1StringLessThanNoCase.html
/usr/share/fix8/html/structFIX8_1_1StringLessThanNoCase.js
/usr/share/fix8/html/structFIX8_1_1StringPtrLessThan-members.html
/usr/share/fix8/html/structFIX8_1_1StringPtrLessThan.html
/usr/share/fix8/html/structFIX8_1_1StringPtrLessThan.js
/usr/share/fix8/html/structFIX8_1_1StringPtrLessThanNoCase-members.html
/usr/share/fix8/html/structFIX8_1_1StringPtrLessThanNoCase.html
/usr/share/fix8/html/structFIX8_1_1StringPtrLessThanNoCase.js
/usr/share/fix8/html/structFIX8_1_1StringRealm-members.html
/usr/share/fix8/html/structFIX8_1_1StringRealm.html
/usr/share/fix8/html/structFIX8_1_1StringRealm.js
/usr/share/fix8/html/structFIX8_1_1StringRealm.png
/usr/share/fix8/html/structFIX8_1_1ThreadException-members.html
/usr/share/fix8/html/structFIX8_1_1ThreadException.html
/usr/share/fix8/html/structFIX8_1_1ThreadException.js
/usr/share/fix8/html/structFIX8_1_1ThreadException.png
/usr/share/fix8/html/structFIX8_1_1f8Allocator_1_1rebind-members.html
/usr/share/fix8/html/structFIX8_1_1f8Allocator_1_1rebind.html
/usr/share/fix8/html/structFIX8_1_1f8Allocator_1_1rebind.js
/usr/share/fix8/html/structFIX8_1_1free__ptr-members.html
/usr/share/fix8/html/structFIX8_1_1free__ptr.html
/usr/share/fix8/html/structFIX8_1_1free__ptr.js
/usr/share/fix8/html/structXmlElement_1_1EntityOrderComp-members.html
/usr/share/fix8/html/structXmlElement_1_1EntityOrderComp.html
/usr/share/fix8/html/structXmlElement_1_1EntityOrderComp.js
/usr/share/fix8/html/tab_a.png
/usr/share/fix8/html/tab_b.png
/usr/share/fix8/html/tab_h.png
/usr/share/fix8/html/tab_s.png
/usr/share/fix8/html/tabs.css
/usr/share/fix8/html/thread_8hpp.html
/usr/share/fix8/html/thread_8hpp.js
/usr/share/fix8/html/thread_8hpp_source.html
/usr/share/fix8/html/tickval_8hpp.html
/usr/share/fix8/html/tickval_8hpp.js
/usr/share/fix8/html/tickval_8hpp_source.html
/usr/share/fix8/html/timer_8hpp.html
/usr/share/fix8/html/timer_8hpp.js
/usr/share/fix8/html/timer_8hpp_source.html
/usr/share/fix8/html/traits_8cpp.html
/usr/share/fix8/html/traits_8cpp_source.html
/usr/share/fix8/html/traits_8hpp.html
/usr/share/fix8/html/traits_8hpp.js
/usr/share/fix8/html/traits_8hpp_source.html
/usr/share/fix8/html/unionFIX8_1_1BDBPersister_1_1KeyDataBuffer_1_1Ubuf-members.html
/usr/share/fix8/html/unionFIX8_1_1BDBPersister_1_1KeyDataBuffer_1_1Ubuf.html
/usr/share/fix8/html/unionFIX8_1_1BDBPersister_1_1KeyDataBuffer_1_1Ubuf.js
/usr/share/fix8/html/usage_8hpp.html
/usr/share/fix8/html/usage_8hpp.js
/usr/share/fix8/html/usage_8hpp_source.html
/usr/share/fix8/html/xml_8cpp.html
/usr/share/fix8/html/xml_8cpp.js
/usr/share/fix8/html/xml_8cpp_source.html
/usr/share/fix8/html/xml_8hpp.html
/usr/share/fix8/html/xml_8hpp.js
/usr/share/fix8/html/xml_8hpp_source.html
/usr/share/fix8/schema/FIX40.xml
/usr/share/fix8/schema/FIX41.xml
/usr/share/fix8/schema/FIX42.xml
/usr/share/fix8/schema/FIX42PERF.xml
/usr/share/fix8/schema/FIX43.xml
/usr/share/fix8/schema/FIX44.xml
/usr/share/fix8/schema/FIX50.xml
/usr/share/fix8/schema/FIX50SP1.xml
/usr/share/fix8/schema/FIX50SP2.xml
/usr/share/fix8/schema/FIXT11.xml
/usr/share/fix8/schema/QUICKFIX-LICENCE
/usr/share/fix8/test/f8_hf_test
/usr/share/fix8/test/hf_client.xml
/usr/share/fix8/test/hf_client_include.xml
/usr/share/fix8/test/hf_server.xml
/usr/share/fix8/test/myfix_client.xml
/usr/share/fix8/test/myfix_server.xml

#%doc
#
%changelog

